import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Header} from '../components/header/Header'
import {Footer} from '../components/footer/Footer'
// import {ThemeProvider} from '../context/ThemeContext'
import {ThemeLayout} from '../components/DarkModelToggle/ThemeLayout'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeLayout>
          <div className="main">
            <Header />
            {children}
            <Footer />
          </div>
        </ThemeLayout>
        
      </body>
    </html>
  );
}
